application: saviors-of-middle-earth
#the below needs to be incremented after each upload to appengine
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

#Items Controller
- url: /
  script: items_controller.app
  secure: always
- url: /search
  script: items_controller.app
  secure: always
- url: /items/add
  script: items_controller.app
  secure: always
  login: required
- url: /items/edit/.*
  script: items_controller.app
  secure: always
  login: required
- url: /items/delete/.*
  script: items_controller.app
  secure: always
  login: required
- url: /items/.*
  script: items_controller.app
  secure: always

#Users Controller
- url: /users/.*/delete
  script: users_controller.app
  login: required
  secure: always
- url: /users/.*/deactivate
  script: users_controller.app
  login: required
  secure: always
- url: /users/.*/promote
  script: users_controller.app
  login: required
  secure: always
- url: /users/.*/
  script: users_controller.app
  secure: always
- url: /users/.*
  script: users_controller.app
  secure: always

#Admin Controller
- url: /admin
  script: admin_controller.app
  login: required
  secure: always
- url: /admin/
  script: admin_controller.app
  login: required
  secure: always
- url: /admin/logs
  script: admin_controller.app
  login: required
  secure: always
- url: /admin/user
  script: admin_controller.app
  login: required
  secure: always

#Static Content
- url: /js/
  static_dir: public/js
  secure: always

- url: /css/
  static_dir: public/css
  secure: always

- url: /images/
  static_dir: public/images
  secure: always

#Not Found Handler (must go last)
- url: /.*
  script: not_found.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
