application: saviors-of-middle-earth
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  script: main.app
  secure: always

- url: /
  static_dir: public

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
